ped_storage:
    adapter:         "%env(STORAGE_ADAPTER)%"
    directory:       "%env(STORAGE_DIRECTORY)%"
    thumbs_prefix:   "%env(STORAGE_THUMBS_PREFIX)%"
    amazon_s3:
        key:         "%env(STORAGE_AMAZON_S3_KEY)%"
        secret:      "%env(STORAGE_AMAZON_S3_SECRET)%"
        region:      "%env(STORAGE_AMAZON_S3_REGION)%"
        endpoint:    "%env(STORAGE_AMAZON_S3_ENDPOINT)%"
        bucket_name: "%env(STORAGE_AMAZON_S3_BUCKET_NAME)%"
        expire_at:   "%env(STORAGE_AMAZON_S3_EXPIRE_AT)%"
