ped_storage:
    amazon_s3:
        aws_key:        %amazon_aws_key%
        aws_secret_key: %amazon_aws_secret_key%
        base_url:       %amazon_s3_base_url%

knp_gaufrette:
    adapters:
        local_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads
        amazon_s3_adapter:
            amazon_s3:
                amazon_s3_id: ped_storage.amazon_s3
                bucket_name:  %amazon_s3_bucket_name%
                create:       false
                options:
                    create: true
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs