ped_storage:
    amazon_s3:
        key:         "%storage_amazon_s3_key%"
        secret:      "%storage_amazon_s3_secret%"
        region:      "%storage_amazon_s3_region%"
        endpoint:    "%storage_amazon_s3_endpoint%"
        bucket_name: "%storage_amazon_s3_bucket_name%"
        directory:   "%storage_amazon_s3_directory%"
        expire_at:   "%storage_amazon_s3_expire_at%"
    local:
        endpoint:    "%storage_local_endpoint%"
        directory:   "%storage_local_directory%"
        thumbs_prefix: "%storage_local_thumbs_prefix%"

knp_gaufrette:
    stream_wrapper:
        protocol: pedstorage
    adapters:
        local_adapter:
            local:
                directory: "%storage_local_directory%"
        amazon_s3_adapter:
            aws_s3:
                service_id:  "ped_storage.aws_s3.client"
                bucket_name: "%storage_amazon_s3_bucket_name%"
                options:
                    create:    true
                    directory: "%storage_amazon_s3_directory%"
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs

liip_imagine:
    data_loader: "loader_%storage_adapter%_data"
    cache: "%storage_adapter%_fs"