ped_storage:
    amazon_s3:
        key:         "%storage_amazon_s3_key%"
        secret:      "%storage_amazon_s3_secret%"
        region:      "%storage_amazon_s3_region%"
        base_url:    "%storage_amazon_s3_base_url%"
        bucket_name: "%storage_amazon_s3_bucket_name%"
        directory:   "%storage_amazon_s3_directory%"
    local:
        directory:   "%storage_local_directory%"

knp_gaufrette:
    adapters:
        local_adapter:
            local:
                directory: "%ped_storage.local.directory%"
        amazon_s3_adapter:
            aws_s3:
                service_id:  "ped_storage.aws_s3.client"
                bucket_name: "%ped_storage.amazon_s3.bucket_name%"
                options:
                    create:    true
                    directory: "%ped_storage.amazon_s3.directory%"
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs

liip_imagine:
    loaders:
        stream.amazon_fs:
            stream:
                wrapper: gaufrette://amazon_fs
        stream.local_fs:
            stream:
                wrapper: gaufrette://local_fs