ped_storage:
    amazon_s3:
        key:      %amazon_s3_key%
        secret:   %amazon_s3_secret%
        region:   %amazon_s3_region%
        base_url: %amazon_s3_base_url%

knp_gaufrette:
    adapters:
        local_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads
        amazon_s3_adapter:
            aws_s3:
                service_id: 'ped_storage.aws_s3.client'
                bucket_name: %amazon_s3_bucket_name%
                options:
                    create:    true
                    directory: 'uploads'
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs

liip_imagine:
    loaders:
        stream.amazon_fs:
            stream:
                wrapper: gaufrette://amazon_fs
        stream.local_fs:
            stream:
                wrapper: gaufrette://local_fs