parameters:
    ped_storage.amazon_s3.class: AmazonS3
    ped_storage.photo_uploader.class: PaneeDesign\StorageBundle\Upload\PhotoUploader

services:
    ped_storage.amazon_s3:
        class: %ped_storage.amazon_s3.class%
        arguments:
            options:
                key:    '%ped_storage.amazon_s3.aws_key%'
                secret: '%ped_storage.amazon_s3.aws_secret_key%'
    ped_storage.amazon_photo_uploader:
        class: %ped_storage.photo_uploader.class%
        arguments: ['@amazon_fs']
    ped_storage.local_photo_uploader:
        class: %ped_storage.photo_uploader.class%
        arguments: ['@local_fs']