parameters:
    ped_storage.amazon_s3.class: AmazonS3
    ped_storage.photo_uploader.class: PaneeDesign\StorageBundle\Upload\PhotoUploader

services:
    ped_storage.amazon_s3:
        class: %ped_storage.amazon_s3.class%
        arguments: [{ key: '%ped_storage.amazon_s3.aws_key%', secret: '%ped_storage.amazon_s3.aws_secret_key%' }]
    ped_storage.photo_uploader:
        class: %ped_storage.photo_uploader.class%
        arguments: ['@photo_storage_filesystem']