parameters:
    ped_storage.aws_s3.client.class:  Aws\S3\S3Client
    ped_storage.photo_uploader.class: PaneeDesign\StorageBundle\Upload\PhotoUploader

services:
    ped_storage.aws_s3.client:
        class: "%ped_storage.aws_s3.client.class%"
        factory: ["%ped_storage.aws_s3.client.class%", 'factory']
        arguments:
            -
                version: latest
                region: %amazon_s3_region%
                credentials:
                    key: %amazon_s3_key%
                    secret: %amazon_s3_secret%
    ped_storage.amazon_photo_uploader:
        class: %ped_storage.photo_uploader.class%
        arguments: ['@amazon_fs']
    ped_storage.local_photo_uploader:
        class: %ped_storage.photo_uploader.class%
        arguments: ['@local_fs']
    ped_storage.liip_imagine.binary.loader.stream.amazon_fs:
        class: "%liip_imagine.binary.loader.stream.class%"
        arguments:
            - 'gaufrette://amazon_fs/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'stream.amazon_fs' }
    ped_storage.liip_imagine.binary.loader.stream.local_fs:
        class: "%liip_imagine.binary.loader.stream.class%"
        arguments:
            - 'gaufrette://local_fs/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'stream.local_fs' }