parameters:
    ped_storage.amazon_s3.class: AmazonS3

services:
    ped_storage.amazon_s3: "%ped_storage.amazon_s3.class%"
    arguments: ["%ped_storage.amazon_s3.aws_key%", "%ped_storage.amazon_s3.aws_secret_key%"]