services:
    ped_storage.uploader:
        class: 'PaneeDesign\StorageBundle\Handler\MediaHandler'
        arguments:
            $filesystem: '@ped_storage.filesystem'
            $liipCacheManager: '@liip_imagine.cache.manager'
        calls:
            -   method: setAwsS3Resolver
                arguments:
                    - '@ped_storage.amazon_public_url_resolver'
        public: true
